"""Word document builder using python-docx."""

import io
from datetime import datetime
from pathlib import Path
from typing import List

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt

from autodoc.core.exceptions import BuilderError
from autodoc.core.models import (
    ContentType,
    DocumentSpec,
    GeneratedContent,
    SectionResult,
)


class DocumentBuilder:
    """Builds Word documents from generated content.

    Uses python-docx to assemble the final document with
    title page, table of contents, and content sections.
    """

    def __init__(self, output_dir: Path = Path("./output")):
        """Initialize the document builder.

        Args:
            output_dir: Directory to save generated documents.
        """
        self.output_dir = output_dir

    async def build(
        self,
        spec: DocumentSpec,
        results: List[SectionResult],
    ) -> Path:
        """Build the Word document from generated content.

        Args:
            spec: Document specification.
            results: List of generated section results.

        Returns:
            Path to the generated document.

        Raises:
            BuilderError: If document building fails.
        """
        try:
            doc = Document()

            # Add title page
            self._add_title_page(doc, spec)

            # Add table of contents placeholder
            self._add_table_of_contents(doc)

            # Add sections
            for result in results:
                self._add_section(doc, result)

            # Save document
            output_path = self._save_document(doc)

            return output_path

        except Exception as e:
            raise BuilderError(f"Document building failed: {e}") from e

    def _add_title_page(self, doc: Document, spec: DocumentSpec) -> None:
        """Add title page to the document."""
        # Add some spacing at the top
        for _ in range(5):
            doc.add_paragraph()

        # Title
        title_para = doc.add_paragraph()
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_run = title_para.add_run(spec.title)
        title_run.font.size = Pt(28)
        title_run.bold = True

        # Subtitle spacing
        doc.add_paragraph()
        doc.add_paragraph()

        # Authors
        author_para = doc.add_paragraph()
        author_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        author_run = author_para.add_run(spec.authors)
        author_run.font.size = Pt(14)

        # Date
        doc.add_paragraph()
        date_para = doc.add_paragraph()
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        date_run = date_para.add_run(datetime.now().strftime("%B %d, %Y"))
        date_run.font.size = Pt(12)

        # Generated by notice
        doc.add_paragraph()
        doc.add_paragraph()
        notice_para = doc.add_paragraph()
        notice_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        notice_run = notice_para.add_run("Generated by Auto Model Documentation")
        notice_run.font.size = Pt(10)
        notice_run.italic = True

        # Page break
        doc.add_page_break()

    def _add_table_of_contents(self, doc: Document) -> None:
        """Add table of contents placeholder."""
        doc.add_heading("Table of Contents", level=1)

        # Note about updating TOC
        para = doc.add_paragraph()
        para.add_run(
            "To update the table of contents: Right-click and select 'Update Field' "
            "or press Ctrl+A then F9 in Microsoft Word."
        ).italic = True

        doc.add_paragraph()

        # Add TOC field (Word will populate this)
        # This creates a placeholder that Word can update
        para = doc.add_paragraph()
        para.add_run("[Table of Contents - Update field to generate]")

        doc.add_page_break()

    def _add_section(self, doc: Document, result: SectionResult) -> None:
        """Add a section to the document."""
        # Section heading with number
        heading_text = f"{result.plan.number}. {result.plan.title}"
        doc.add_heading(heading_text, level=1)

        # Add content blocks
        for content in result.contents:
            self._add_content(doc, content)

        # Add error notes if any
        if result.errors:
            para = doc.add_paragraph()
            para.add_run("Note: Some content could not be generated:").italic = True
            for error in result.errors:
                doc.add_paragraph(f"  - {error}", style="List Bullet")

        # Add spacing between sections
        doc.add_paragraph()

    def _add_content(self, doc: Document, content: GeneratedContent) -> None:
        """Add a content block to the document."""
        if content.block_type == ContentType.NARRATIVE:
            self._add_narrative(doc, content.content)

        elif content.block_type == ContentType.TABLE:
            self._add_table(doc, content.content)

        elif content.block_type == ContentType.CHART:
            self._add_chart(doc, content.content, content.metadata)

        elif content.block_type == ContentType.IMAGE:
            self._add_embedded_image(doc, content.content, content.metadata)

        elif content.block_type in (ContentType.BULLET_LIST, ContentType.NUMBERED_LIST):
            self._add_list(doc, content)

    def _add_narrative(self, doc: Document, text: str) -> None:
        """Add narrative paragraphs to the document."""
        # Split by double newlines to get paragraphs
        paragraphs = text.split("\n\n")

        for para_text in paragraphs:
            if para_text.strip():
                # Clean up the text
                clean_text = " ".join(para_text.split())
                para = doc.add_paragraph(clean_text)
                para.paragraph_format.space_after = Pt(12)

    def _add_table(self, doc: Document, data: dict) -> None:
        """Add a table to the document."""
        caption = data.get("caption", "")
        columns = data.get("columns", [])
        rows = data.get("rows", [])

        if not columns or not rows:
            return

        # Add caption
        if caption:
            caption_para = doc.add_paragraph()
            caption_run = caption_para.add_run(caption)
            caption_run.bold = True
            caption_para.paragraph_format.space_after = Pt(6)

        # Create table
        table = doc.add_table(rows=1, cols=len(columns))
        table.style = "Table Grid"

        # Header row
        header_cells = table.rows[0].cells
        for i, col in enumerate(columns):
            header_cells[i].text = str(col)
            # Bold header
            for paragraph in header_cells[i].paragraphs:
                for run in paragraph.runs:
                    run.bold = True

        # Data rows
        for row_data in rows:
            row_cells = table.add_row().cells
            for i, col in enumerate(columns):
                value = row_data.get(col, "") if isinstance(row_data, dict) else ""
                row_cells[i].text = str(value)

        # Add spacing after table
        doc.add_paragraph()

    def _add_chart(self, doc: Document, image_bytes: bytes, metadata: dict) -> None:
        """Add a chart image to the document."""
        if not image_bytes:
            return

        # Add chart title if available
        title = metadata.get("title", "")
        if title:
            title_para = doc.add_paragraph()
            title_run = title_para.add_run(title)
            title_run.bold = True
            title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add the image
        image_stream = io.BytesIO(image_bytes)
        doc.add_picture(image_stream, width=Inches(6))

        # Center the image
        last_paragraph = doc.paragraphs[-1]
        last_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add spacing
        doc.add_paragraph()

    def _add_embedded_image(self, doc: Document, image_bytes: bytes, metadata: dict) -> None:
        """Add an embedded MLflow image to the document."""
        if not image_bytes:
            return

        # Add image title if available
        title = metadata.get("title", "")
        if title:
            title_para = doc.add_paragraph()
            title_run = title_para.add_run(title)
            title_run.bold = True
            title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add source path as caption
        path = metadata.get("path", "")
        if path:
            caption_para = doc.add_paragraph()
            caption_run = caption_para.add_run(f"Source: {path}")
            caption_run.italic = True
            caption_run.font.size = Pt(9)
            caption_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add the image
        image_stream = io.BytesIO(image_bytes)
        doc.add_picture(image_stream, width=Inches(6))

        # Center the image
        last_paragraph = doc.paragraphs[-1]
        last_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add spacing
        doc.add_paragraph()

    def _add_list(self, doc: Document, content: GeneratedContent) -> None:
        """Add a list to the document."""
        # Handle both dict format (with title) and list format (legacy)
        if isinstance(content.content, dict):
            items = content.content.get("items", [])
            title = content.content.get("title", "")
        else:
            items = content.content
            title = ""

        if not items:
            return

        # Add title as subheading if provided
        if title:
            title_para = doc.add_paragraph()
            title_run = title_para.add_run(title)
            title_run.bold = True
            title_para.paragraph_format.space_after = Pt(6)

        # Choose style based on list type
        style = (
            "List Bullet"
            if content.block_type == ContentType.BULLET_LIST
            else "List Number"
        )

        for item in items:
            if item and item.strip():
                doc.add_paragraph(item.strip(), style=style)

        # Add spacing after list
        doc.add_paragraph()

    def _save_document(self, doc: Document) -> Path:
        """Save the document to the output directory."""
        # Ensure output directory exists
        self.output_dir.mkdir(parents=True, exist_ok=True)

        # Generate filename with timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"model_docs_{timestamp}.docx"
        output_path = self.output_dir / filename

        # Save
        doc.save(output_path)

        return output_path
