"""Word document builder using python-docx."""

import io
import os
import re
from datetime import datetime
from pathlib import Path
from typing import List

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt

from autodoc.core.exceptions import BuilderError
from autodoc.core.models import (
    ContentType,
    DocumentSpec,
    GeneratedContent,
    SectionResult,
)
from autodoc.generation.citations import (
    CITATION_MARKER_PATTERN,
    CitationRegistry,
    build_mlflow_summary_citation_id,
    parse_citation_id,
)


class DocumentBuilder:
    """Builds Word documents from generated content.

    Uses python-docx to assemble the final document with
    title page, table of contents, and content sections.
    """

    def __init__(self, output_dir: Path = Path("./output")):
        """Initialize the document builder.

        Args:
            output_dir: Directory to save generated documents.
        """
        self.output_dir = output_dir

    async def build(
        self,
        spec: DocumentSpec,
        results: List[SectionResult],
    ) -> Path:
        """Build the Word document from generated content.

        Args:
            spec: Document specification.
            results: List of generated section results.

        Returns:
            Path to the generated document.

        Raises:
            BuilderError: If document building fails.
        """
        try:
            doc = Document()
            self.formatting = spec.formatting or {}
            registry = CitationRegistry(tracking_uri=os.environ.get("MLFLOW_TRACKING_URI"))

            # Add title page
            self._add_title_page(doc, spec)

            # Add table of contents placeholder
            self._add_table_of_contents(doc)

            # Add sections
            for result in results:
                self._add_section(doc, result, registry)

            # Add bibliography if citations exist
            if registry.list_entries():
                self._add_bibliography(doc, registry)

            # Save document
            output_path = self._save_document(doc)

            return output_path

        except Exception as e:
            raise BuilderError(f"Document building failed: {e}") from e

    def _add_title_page(self, doc: Document, spec: DocumentSpec) -> None:
        """Add title page to the document."""
        # Add some spacing at the top
        for _ in range(5):
            doc.add_paragraph()

        # Title
        title_para = doc.add_paragraph()
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_run = title_para.add_run(spec.title)
        title_size = self.formatting.get("title_font_size", 28)
        title_run.font.size = Pt(title_size)
        title_run.bold = True

        # Subtitle spacing
        doc.add_paragraph()
        doc.add_paragraph()

        # Authors
        author_para = doc.add_paragraph()
        author_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        author_run = author_para.add_run(spec.authors)
        author_size = self.formatting.get("author_font_size", 14)
        author_run.font.size = Pt(author_size)

        # Date
        doc.add_paragraph()
        date_para = doc.add_paragraph()
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        date_run = date_para.add_run(datetime.now().strftime("%B %d, %Y"))
        date_size = self.formatting.get("date_font_size", 12)
        date_run.font.size = Pt(date_size)

        # Generated by notice
        doc.add_paragraph()
        doc.add_paragraph()
        notice_para = doc.add_paragraph()
        notice_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        notice_run = notice_para.add_run("Generated by Auto Model Documentation")
        notice_size = self.formatting.get("notice_font_size", 10)
        notice_run.font.size = Pt(notice_size)
        notice_run.italic = True

        # Page break
        doc.add_page_break()

    def _add_table_of_contents(self, doc: Document) -> None:
        """Add table of contents placeholder."""
        doc.add_heading("Table of Contents", level=1)

        # Note about updating TOC
        para = doc.add_paragraph()
        para.add_run(
            "To update the table of contents: Right-click and select 'Update Field' "
            "or press Ctrl+A then F9 in Microsoft Word."
        ).italic = True

        doc.add_paragraph()

        # Add TOC field (Word will populate this)
        # This creates a placeholder that Word can update
        para = doc.add_paragraph()
        para.add_run("[Table of Contents - Update field to generate]")

        doc.add_page_break()

    def _merge_citations(self, citations: List[str], extra: List[str]) -> List[str]:
        merged: List[str] = []
        seen = set()
        for cid in list(citations or []) + list(extra or []):
            if not cid or cid in seen:
                continue
            seen.add(cid)
            merged.append(cid)
        return merged

    def _strip_citation_markers(self, text: str) -> tuple[str, List[str]]:
        if not text:
            return text, []

        found_ids: List[str] = []

        def _replace(match) -> str:
            citation_id = match.group(1)
            if citation_id:
                found_ids.append(citation_id)
            return ""

        cleaned = CITATION_MARKER_PATTERN.sub(_replace, text)
        cleaned = " ".join(cleaned.split())
        return cleaned, found_ids

    def _strip_markers_from_table(
        self, table_data: dict, found_ids: List[str]
    ) -> dict:
        if not isinstance(table_data, dict):
            return table_data

        cleaned = dict(table_data)
        caption = cleaned.get("caption")
        if isinstance(caption, str):
            cleaned_caption, found = self._strip_citation_markers(caption)
            cleaned["caption"] = cleaned_caption
            found_ids.extend(found)

        columns = cleaned.get("columns")
        if isinstance(columns, list):
            cleaned_columns = []
            for col in columns:
                if isinstance(col, str):
                    cleaned_col, found = self._strip_citation_markers(col)
                    cleaned_columns.append(cleaned_col)
                    found_ids.extend(found)
                else:
                    cleaned_columns.append(col)
            cleaned["columns"] = cleaned_columns

        rows = cleaned.get("rows")
        if isinstance(rows, list):
            cleaned_rows = []
            for row in rows:
                if not isinstance(row, dict):
                    cleaned_rows.append(row)
                    continue
                cleaned_row = {}
                for key, value in row.items():
                    if isinstance(value, str):
                        cleaned_value, found = self._strip_citation_markers(value)
                        cleaned_row[key] = cleaned_value
                        found_ids.extend(found)
                    else:
                        cleaned_row[key] = value
                cleaned_rows.append(cleaned_row)
            cleaned["rows"] = cleaned_rows

        return cleaned

    def _sanitize_content_for_section(
        self, content: GeneratedContent
    ) -> tuple[GeneratedContent, List[str], dict]:
        metadata = dict(content.metadata or {})
        citations = list(metadata.get("citations", []) or [])
        details = dict(metadata.get("citation_details", {}) or {})
        found_ids: List[str] = []

        if content.block_type == ContentType.NARRATIVE:
            cleaned_text, found = self._strip_citation_markers(content.content or "")
            found_ids.extend(found)
            safe_metadata = dict(metadata)
            safe_metadata["citations"] = []
            safe_metadata["citation_details"] = {}
            safe_content = cleaned_text
            block_citations = []
            block_details = {}
        elif content.block_type in (ContentType.BULLET_LIST, ContentType.NUMBERED_LIST):
            cleaned_items: List[str] = []
            # Handle both dict format (with title) and list format (legacy)
            if isinstance(content.content, dict):
                raw_items = content.content.get("items", [])
                raw_title = content.content.get("title", "")
            else:
                raw_items = content.content or []
                raw_title = ""

            for item in raw_items:
                cleaned_item, found = self._strip_citation_markers(item)
                found_ids.extend(found)
                cleaned_items.append(cleaned_item)

            # Also strip markers from title if present
            cleaned_title = ""
            if raw_title:
                cleaned_title, found = self._strip_citation_markers(raw_title)
                found_ids.extend(found)

            safe_metadata = dict(metadata)
            safe_metadata["citations"] = []
            safe_metadata["citation_details"] = {}
            # Preserve dict format if original was dict
            if isinstance(content.content, dict):
                safe_content = {"items": cleaned_items, "title": cleaned_title}
            else:
                safe_content = cleaned_items
            block_citations = []
            block_details = {}
        elif content.block_type == ContentType.TABLE:
            safe_metadata = dict(metadata)
            safe_content = self._strip_markers_from_table(
                content.content or {}, found_ids
            )
            block_citations = self._merge_citations(citations, found_ids)
            block_details = {
                cid: details[cid] for cid in block_citations if cid in details
            }
            safe_metadata["citations"] = block_citations
            safe_metadata["citation_details"] = block_details
        elif content.block_type in (ContentType.CHART, ContentType.IMAGE):
            safe_metadata = dict(metadata)
            title = safe_metadata.get("title")
            if isinstance(title, str):
                cleaned_title, found = self._strip_citation_markers(title)
                safe_metadata["title"] = cleaned_title
                found_ids.extend(found)
            safe_content = content.content
            block_citations = self._merge_citations(citations, found_ids)
            block_details = {
                cid: details[cid] for cid in block_citations if cid in details
            }
            safe_metadata["citations"] = block_citations
            safe_metadata["citation_details"] = block_details
        else:
            safe_metadata = dict(metadata)
            safe_content = content.content
            block_citations = self._merge_citations(citations, found_ids)
            block_details = {
                cid: details[cid] for cid in block_citations if cid in details
            }
            safe_metadata["citations"] = block_citations
            safe_metadata["citation_details"] = block_details

        section_citations = self._merge_citations(citations, found_ids)
        section_details = {cid: details[cid] for cid in details}

        cleaned_content = GeneratedContent(
            block_type=content.block_type,
            content=safe_content,
            metadata=safe_metadata,
        )

        return cleaned_content, section_citations, section_details

    def _normalize_section_citations(
        self, citation_ids: List[str], citation_details: dict
    ) -> tuple[List[str], dict]:
        if not citation_ids:
            return [], {}

        experiment_by_run: dict = {}
        for detail in citation_details.values():
            run_id = detail.get("run_id")
            experiment_id = detail.get("experiment_id")
            if run_id and experiment_id:
                experiment_by_run[run_id] = experiment_id

        normalized_ids: List[str] = []
        normalized_details: dict = {}
        for citation_id in citation_ids:
            parsed = parse_citation_id(citation_id)
            if str(parsed.get("type", "")).startswith("mlflow_"):
                run_id = parsed.get("run_id")
                if run_id:
                    summary_id = build_mlflow_summary_citation_id(run_id)
                    normalized_ids.append(summary_id)
                    if summary_id not in normalized_details:
                        normalized_details[summary_id] = {
                            "type": "mlflow_summary",
                            "run_id": run_id,
                            "experiment_id": experiment_by_run.get(run_id),
                        }
                    continue
            normalized_ids.append(citation_id)
            if citation_id in citation_details and citation_id not in normalized_details:
                normalized_details[citation_id] = citation_details[citation_id]

        deduped: List[str] = []
        seen = set()
        for cid in normalized_ids:
            if cid in seen:
                continue
            seen.add(cid)
            deduped.append(cid)

        filtered_details = {
            cid: normalized_details.get(cid, {})
            for cid in deduped
            if cid in normalized_details
        }

        return deduped, filtered_details

    def _add_section(
        self, doc: Document, result: SectionResult, registry: CitationRegistry
    ) -> None:
        """Add a section to the document."""
        # Section heading with number
        heading_text = f"{result.plan.number}. {result.plan.title}"
        heading_para = doc.add_heading(heading_text, level=1)
        heading_size = self.formatting.get("heading_font_size")
        if heading_size:
            for run in heading_para.runs:
                run.font.size = Pt(heading_size)

        section_citation_ids: List[str] = []
        section_citation_details: dict = {}

        # Add content blocks
        for content in result.contents:
            cleaned_content, citation_ids, citation_details = self._sanitize_content_for_section(
                content
            )
            section_citation_ids.extend(citation_ids)
            section_citation_details.update(citation_details)
            self._add_content(doc, cleaned_content, registry)

        # Add error notes if any
        if result.errors:
            para = doc.add_paragraph()
            para.add_run("Note: Some content could not be generated:").italic = True
            for error in result.errors:
                doc.add_paragraph(f"  - {error}", style="List Bullet")

        # Register all section citations for the bibliography (but don't display "Sources:" block)
        section_citation_ids, section_citation_details = self._normalize_section_citations(
            section_citation_ids, section_citation_details
        )
        for cid in section_citation_ids:
            registry.register(cid, section_citation_details.get(cid))

        # Add spacing between sections
        doc.add_paragraph()

    def _add_content(
        self, doc: Document, content: GeneratedContent, registry: CitationRegistry
    ) -> None:
        """Add a content block to the document."""
        if content.block_type == ContentType.NARRATIVE:
            self._add_narrative(doc, content.content, content.metadata, registry)

        elif content.block_type == ContentType.TABLE:
            self._add_table(doc, content.content, content.metadata, registry)

        elif content.block_type == ContentType.CHART:
            self._add_chart(doc, content.content, content.metadata, registry)

        elif content.block_type == ContentType.IMAGE:
            self._add_embedded_image(doc, content.content, content.metadata, registry)

        elif content.block_type in (ContentType.BULLET_LIST, ContentType.NUMBERED_LIST):
            self._add_list(doc, content, registry)

    def _add_narrative(
        self,
        doc: Document,
        text: str,
        metadata: dict,
        registry: CitationRegistry,
    ) -> None:
        """Add narrative paragraphs to the document."""
        # Split by double newlines to get paragraphs
        paragraphs = text.split("\n\n")

        for para_text in paragraphs:
            if para_text.strip():
                # Clean up the text
                clean_text = " ".join(para_text.split())
                para = doc.add_paragraph()
                narrative_size = self.formatting.get("narrative_font_size")
                self._append_text_with_citations(
                    para,
                    clean_text,
                    metadata or {},
                    registry,
                    font_size=narrative_size,
                )
                para.paragraph_format.space_after = Pt(12)

    def _add_table(
        self,
        doc: Document,
        data: dict,
        metadata: dict,
        registry: CitationRegistry,
    ) -> None:
        """Add a table to the document."""
        caption = data.get("caption", "")
        columns = data.get("columns", [])
        rows = data.get("rows", [])

        if not columns or not rows:
            return

        # Add caption with citations (citations only in caption, not in table rows)
        if caption:
            caption_para = doc.add_paragraph()
            self._append_text_with_citations(
                caption_para,
                caption,
                metadata or {},
                registry,
                bold_text=True,
                include_extra=True,  # Include all citations in caption
            )
            caption_para.paragraph_format.space_after = Pt(6)
        elif metadata and metadata.get("citations"):
            # No caption but has citations - add a source line above table
            source_para = doc.add_paragraph()
            source_para.add_run("Table")
            self._append_citations_only(source_para, metadata, registry)
            source_para.paragraph_format.space_after = Pt(6)

        # Create table
        table = doc.add_table(rows=1, cols=len(columns))
        table.style = self.formatting.get("table_style", "Table Grid")

        # Header row
        header_cells = table.rows[0].cells
        for i, col in enumerate(columns):
            header_cells[i].text = str(col)
            # Bold header
            for paragraph in header_cells[i].paragraphs:
                for run in paragraph.runs:
                    run.bold = True

        # Data rows
        for row_data in rows:
            row_cells = table.add_row().cells
            for i, col in enumerate(columns):
                value = row_data.get(col, "") if isinstance(row_data, dict) else ""
                row_cells[i].text = str(value)

        # Add spacing after table
        doc.add_paragraph()

    def _add_chart(
        self,
        doc: Document,
        image_bytes: bytes,
        metadata: dict,
        registry: CitationRegistry,
    ) -> None:
        """Add a chart image to the document."""
        if not image_bytes:
            return

        # Add chart title if available
        title = metadata.get("title", "")
        if title:
            title_para = doc.add_paragraph()
            self._append_text_with_citations(
                title_para,
                title,
                metadata or {},
                registry,
                bold_text=True,
            )
            title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add the image
        image_stream = io.BytesIO(image_bytes)
        doc.add_picture(image_stream, width=Inches(6))

        # Center the image
        last_paragraph = doc.paragraphs[-1]
        last_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add source line if citations exist but no title
        if not title and metadata and metadata.get("citations"):
            source_para = doc.add_paragraph()
            source_para.add_run("Source: ")
            self._append_citations_only(source_para, metadata, registry)
            source_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add spacing
        doc.add_paragraph()

    def _add_embedded_image(
        self,
        doc: Document,
        image_bytes: bytes,
        metadata: dict,
        registry: CitationRegistry,
    ) -> None:
        """Add an embedded MLflow image to the document."""
        if not image_bytes:
            return

        # Add image title if available
        title = metadata.get("title", "")
        if title:
            title_para = doc.add_paragraph()
            self._append_text_with_citations(
                title_para,
                title,
                metadata or {},
                registry,
                bold_text=True,
            )
            title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add the image
        image_stream = io.BytesIO(image_bytes)
        doc.add_picture(image_stream, width=Inches(6))

        # Center the image
        last_paragraph = doc.paragraphs[-1]
        last_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add spacing
        doc.add_paragraph()

    def _add_list(
        self, doc: Document, content: GeneratedContent, registry: CitationRegistry
    ) -> None:
        """Add a list to the document."""
        # Handle both dict format (with title) and list format (legacy)
        if isinstance(content.content, dict):
            items = content.content.get("items", [])
            title = content.content.get("title", "")
        else:
            items = content.content
            title = ""

        if not items:
            return

        # Add title as subheading if provided
        if title:
            title_para = doc.add_paragraph()
            self._append_text_with_citations(
                title_para,
                title,
                content.metadata or {},
                registry,
                bold_text=True,
            )
            title_para.paragraph_format.space_after = Pt(6)

        # Choose style based on list type
        style = (
            "List Bullet"
            if content.block_type == ContentType.BULLET_LIST
            else "List Number"
        )

        for item in items:
            if item and item.strip():
                para = doc.add_paragraph(style=style)
                self._append_text_with_citations(
                    para,
                    item.strip(),
                    content.metadata or {},
                    registry,
                    include_extra=False,
                )

        if content.metadata and content.metadata.get("citations"):
            source_para = doc.add_paragraph()
            source_para.add_run("Source: ")
            self._append_citations_only(source_para, content.metadata, registry)

        # Add spacing after list
        doc.add_paragraph()

    def _append_text_with_citations(
        self,
        para,
        text: str,
        metadata: dict,
        registry: CitationRegistry,
        bold_text: bool = False,
        font_size: int | None = None,
        include_extra: bool = True,
    ) -> None:
        details = metadata.get("citation_details", {}) if metadata else {}
        citation_ids = metadata.get("citations", []) if metadata else []
        used_ids = []

        last_index = 0
        for match in CITATION_MARKER_PATTERN.finditer(text or ""):
            if match.start() > last_index:
                run = para.add_run(text[last_index : match.start()])
                run.bold = bold_text
                if font_size:
                    run.font.size = Pt(font_size)
            citation_id = match.group(1)
            registry.register(citation_id, details.get(citation_id))
            used_ids.append(citation_id)
            # Add citation as superscript number
            number = registry.get_number(citation_id)
            run = para.add_run(str(number))
            run.font.superscript = True
            last_index = match.end()

        if last_index < len(text):
            run = para.add_run(text[last_index:])
            run.bold = bold_text
            if font_size:
                run.font.size = Pt(font_size)

        extra_ids = [cid for cid in citation_ids if cid not in used_ids]
        if include_extra and extra_ids:
            self._append_citations_only(
                para,
                {"citations": extra_ids, "citation_details": details},
                registry,
            )

    def _append_citations_only(
        self, para, metadata: dict, registry: CitationRegistry
    ) -> None:
        details = metadata.get("citation_details", {}) if metadata else {}
        citation_ids = metadata.get("citations", []) if metadata else []
        seen = set()
        numbers = []
        for citation_id in citation_ids:
            if citation_id in seen:
                continue
            seen.add(citation_id)
            registry.register(citation_id, details.get(citation_id))
            number = registry.get_number(citation_id)
            numbers.append(number)
        # Sort and display as superscript numbers
        for idx, number in enumerate(sorted(numbers)):
            if idx == 0:
                para.add_run(" ")
            else:
                para.add_run(",")
            run = para.add_run(str(number))
            run.font.superscript = True

    def _add_bibliography(self, doc: Document, registry: CitationRegistry) -> None:
        doc.add_heading("References", level=1)
        for idx, (display_id, entry) in enumerate(registry.list_entries()):
            para = doc.add_paragraph()
            # Number in brackets
            run = para.add_run(f"[{idx + 1}] ")
            run.bold = True

            # Build single-line reference
            parts = []
            if entry.type == "mlflow_artifact":
                parts.append(display_id)
                parts.append(f"Artifact: {entry.artifact_path}")
            elif entry.type in {"mlflow_run", "mlflow_summary", "mlflow_metric", "mlflow_param", "mlflow_tag"}:
                parts.append(display_id)
                parts.append("Model Run")
            elif entry.type == "code_file":
                # Format code reference - strip __init__ and similar dunder methods
                code_path = entry.code_path or ""
                code_symbol = entry.code_symbol or ""

                # Clean up symbol - remove __init__, __call__, etc.
                clean_symbol = code_symbol
                clean_symbol = clean_symbol.replace(".__init__", "")
                clean_symbol = clean_symbol.replace(".__call__", "")
                clean_symbol = clean_symbol.replace(".__new__", "")

                if code_path and clean_symbol:
                    parts.append(f"Code: {code_path}#{clean_symbol}")
                elif code_path:
                    parts.append(f"Code: {code_path}")
                else:
                    # Fallback: clean up display_id if it contains the info
                    clean_display = display_id
                    # Remove redundant "Code:" prefixes if multiple
                    clean_display = re.sub(r',\s*@?Code:', ', ', clean_display)
                    clean_display = re.sub(r';\s*@?Code:', '; ', clean_display)
                    clean_display = clean_display.replace(".__init__", "")
                    clean_display = clean_display.replace(".__call__", "")
                    clean_display = clean_display.replace(".__new__", "")
                    parts.append(clean_display)
            else:
                # For unknown types, clean up the display_id
                clean_display = display_id
                clean_display = re.sub(r',\s*@?Code:', ', ', clean_display)
                clean_display = re.sub(r';\s*@?Code:', '; ', clean_display)
                clean_display = clean_display.replace(".__init__", "")
                parts.append(clean_display)

            if entry.experiment_name:
                parts.append(f"Experiment: {entry.experiment_name}")
            if entry.run_name:
                parts.append(f"Run: {entry.run_name}")
            if entry.run_url:
                parts.append(f"Link: {entry.run_url}")
            para.add_run(" | ".join(parts))

    def _save_document(self, doc: Document) -> Path:
        """Save the document to the output directory."""
        # Ensure output directory exists
        self.output_dir.mkdir(parents=True, exist_ok=True)

        # Generate filename with timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"model_docs_{timestamp}.docx"
        output_path = self.output_dir / filename

        # Save
        doc.save(output_path)

        return output_path
